apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jira-dev
  namespace: jira
spec:
  project: default
  sources:
    # 1️⃣ Public Helm chart repo
    - repoURL: https://atlassian.github.io/data-center-helm-charts
      chart: jira
      targetRevision: 1.16.1
      helm:
        valueFiles:
          - $values/Values-jira.yaml   # 👈 reference to 2nd repo

    # 2️⃣ Private repo with values
    - repoURL: git@github.com:bsk111675/Jira-data-center-helm-charts.git
      targetRevision: main
      ref: values   # 👈 define alias "values"
  destination:
    server: https://kubernetes.default.svc
    namespace: jira
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
